"use client";

import React, { useCallback, useEffect, useRef, useState } from "react";
import type { TargetLang } from "@/lib/types";
import aiIcon from "@/icons/ai.svg";
import closeIcon from "@/icons/close.svg";
import { maskedIconStyle } from "@/components/buttonStyles";
import styles from "./OnboardingGuide.module.css";

type Props = {
  open: boolean;
  targetLang: TargetLang;
  onClose: () => void;
};

const COPY = {
  zh: {
    label: "使用指南",
    skip: "跳过",
    previous: "上一步",
    next: "下一步",
    start: "开始",
    close: "关闭指南",
    steps: [
      {
        title: "欢迎使用",
        description: "输入一篇日语文章，AI 会帮你整理学习内容。",
        note: "支持自定义或者AI生成的等各种文本。"
      },
      {
        title: "输入文章",
        description: "粘贴一篇日语文章，或让 AI 帮你生成，然后点击'分析'按键。",
        note: "支持不同 JLPT 等级。"
      },
      {
        title: "查看分析结果",
        description: "AI分析完成后，词汇、语法和翻译会显示在右侧。",
        note: "鼠标放在卡片上可以实现更多操作。",
      },
      {
        title: "继续提问",
        description: "选中不理解的部分，随时向 AI 提问并继续追问。",
        note: "单词、语法和左侧选中的句子都可以问 AI。",
      },
    ],
  },
  en: {
    label: "Quick guide",
    skip: "Skip",
    previous: "Back",
    next: "Next",
    start: "Start",
    close: "Close guide",
    steps: [
      {
        title: "Welcome",
        description: "Enter a Japanese article, and AI will organize the learning content for you.",
        note: "Use your own text or content generated by AI.",
      },
      {
        title: "Enter an article",
        description: "Paste a Japanese article or let AI generate one, then click Analyze.",
        note: "Supports different JLPT levels.",
      },
      {
        title: "View the analysis",
        description: "Once the analysis is complete, vocabulary, grammar, and translation appear on the right.",
        note: "Hover over a card to access more actions.",
      },
      {
        title: "Ask follow-up questions",
        description: "Select anything you don't understand to ask AI and continue the conversation.",
        note: "Ask AI about vocabulary, grammar, or sentences selected in the left panel.",
      },
    ],
  },
} as const;

/** A lightweight guide that teaches the workflow without mirroring the live UI. */
export function OnboardingGuide({ open, targetLang, onClose }: Props) {
  const [step, setStep] = useState(0);
  const dialogRef = useRef<HTMLDivElement>(null);
  const copy = COPY[targetLang];
  const isLastStep = step === copy.steps.length - 1;

  const closeGuide = useCallback(() => {
    setStep(0);
    onClose();
  }, [onClose]);

  useEffect(() => {
    if (!open) return;

    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    requestAnimationFrame(() => dialogRef.current?.focus());

    function handleKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") closeGuide();
      if (event.key === "ArrowLeft") setStep((current) => Math.max(0, current - 1));
      if (event.key === "ArrowRight") {
        setStep((current) => Math.min(copy.steps.length - 1, current + 1));
      }
    }

    window.addEventListener("keydown", handleKeyDown);
    return () => {
      document.body.style.overflow = previousOverflow;
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [closeGuide, copy.steps.length, open]);

  if (!open) return null;

  return (
    <div className={styles.overlay} onMouseDown={closeGuide}>
      <div
        ref={dialogRef}
        className={styles.dialog}
        role="dialog"
        aria-modal="true"
        aria-labelledby="onboarding-title"
        tabIndex={-1}
        onMouseDown={(event) => event.stopPropagation()}
      >
        <header className={styles.header}>
          <span className={styles.eyebrow}>{copy.label}</span>
          <button
            type="button"
            className={`${styles.closeButton} btn-interactive`}
            onClick={closeGuide}
            aria-label={copy.close}
            title={copy.close}
          >
            <span aria-hidden="true" style={maskedIconStyle(closeIcon.src, 18)} />
          </button>
        </header>

        <div className={styles.content}>
          <div className={styles.visual} aria-hidden="true">
            {step === 0 && <WelcomeIllustration />}
            {step === 1 && <AnalyzeIllustration />}
            {step === 2 && <KnowledgeIllustration />}
            {step === 3 && <ChatIllustration />}
          </div>

          <section className={styles.copy} key={`${targetLang}-${step}`}>
            <span className={styles.stepNumber}>0{step + 1}</span>
            <h2 id="onboarding-title">{copy.steps[step].title}</h2>
            <p className={styles.description}>{copy.steps[step].description}</p>
            <p className={styles.note}>{copy.steps[step].note}</p>
          </section>
        </div>

        <footer className={styles.footer}>
          <button type="button" className={styles.skipButton} onClick={closeGuide}>
            {copy.skip}
          </button>
          <div className={styles.dots} aria-label={`${step + 1} / ${copy.steps.length}`}>
            {copy.steps.map((item, index) => (
              <button
                type="button"
                key={item.title}
                className={`${styles.dot} ${index === step ? styles.dotActive : ""}`}
                onClick={() => setStep(index)}
                aria-label={`${index + 1}`}
                aria-current={index === step ? "step" : undefined}
              />
            ))}
          </div>
          <div className={styles.actions}>
            {step > 0 && (
              <button
                type="button"
                className={`${styles.secondaryButton} btn-interactive`}
                onClick={() => setStep((current) => current - 1)}
              >
                {copy.previous}
              </button>
            )}
            <button
              type="button"
              className={`${styles.primaryButton} btn-interactive`}
              onClick={() => (isLastStep ? closeGuide() : setStep((current) => current + 1))}
            >
              {isLastStep ? copy.start : copy.next}
              {!isLastStep && <span aria-hidden="true">→</span>}
            </button>
          </div>
        </footer>
      </div>
    </div>
  );
}

function AiSpark() {
  return (
    <div className={styles.spark}>
      <span aria-hidden="true" style={maskedIconStyle(aiIcon.src, 24)} />
    </div>
  );
}

function ArticleCard({ highlighted = false }: { highlighted?: boolean }) {
  return (
    <div className={styles.articleCard}>
      <div className={styles.paperHeader}><span /><span /></div>
      <div className={styles.jpLine}>新しい言葉を学ぶことは</div>
      <div className={styles.jpLine}>
        世界を{highlighted ? <mark>広げる</mark> : "広げる"}ことです。
      </div>
      <div className={styles.textLine} />
      <div className={`${styles.textLine} ${styles.shortLine}`} />
    </div>
  );
}

function WelcomeIllustration() {
  return (
    <div className={styles.workflow}>
      <ArticleCard />
      <div className={styles.connector}>↓</div>
      <AiSpark />
      <div className={styles.connector}>↓</div>
      <div className={styles.miniCards}>
        <span>あ</span><span>文</span><span>訳</span>
      </div>
    </div>
  );
}

function AnalyzeIllustration() {
  return (
    <div className={styles.analyzeFlow}>
      <ArticleCard />
      <div className={styles.levels}>
        <span>N5</span><span>N4</span><span className={styles.activeLevel}>N2</span>
      </div>
      <div className={styles.analyzeButton}>
        <span aria-hidden="true" style={maskedIconStyle(aiIcon.src, 14)} />
        Analyze
      </div>
    </div>
  );
}

function KnowledgeIllustration() {
  return (
    <div className={styles.knowledgeFlow}>
      <AiSpark />
      <div className={`${styles.knowledgeCard} ${styles.vocabCard}`}>
        <strong>Vocabulary</strong><span>進化</span><span>想像</span><span>協力</span>
      </div>
      <div className={`${styles.knowledgeCard} ${styles.grammarCard}`}>
        <strong>Grammar</strong><span>〜すぎる</span><span>〜ことになる</span>
      </div>
      <div className={`${styles.knowledgeCard} ${styles.translationCard}`}>
        <strong>Translation</strong><i /><i /><i className={styles.shortLine} />
      </div>
    </div>
  );
}

function ChatIllustration() {
  return (
    <div className={styles.chatFlow}>
      <ArticleCard highlighted />
      <div className={styles.chatLine} />
      <div className={styles.chatCard}>
        <div className={styles.chatTitle}><AiSpark /><strong>AI Chat</strong></div>
        <div className={styles.userBubble}>「広げる」はどういう意味？</div>
        <div className={styles.aiBubble}>意味と使い方を、例文と一緒に説明します。</div>
        <div className={styles.chatTags}><span>解释</span><span>例文</span><span>Follow up</span></div>
      </div>
    </div>
  );
}
